x-bitcoin-build: &build-bitcoin
  user: ${DOCKER_UID_GID} # should be the same as local user
  build:
    context: ./docker/bitcoin
    args:
      GIT_URL: ${BITCOIN_GIT_URL:-https://github.com/bitcoin/bitcoin.git}
      GIT_BRANCH: ${BITCOIN_GIT_BRANCH:-v27.1}
      NJOBS: ${NJOBS:-4}

x-electrs-build: &build-electrs
  build:
    context: ./docker/electrs
    args:
      GIT_URL: ${ELECTRS_GIT_URL:-https://github.com/romanz/electrs}
      GIT_BRANCH: ${ELECTRS_GIT_BRANCH:-master}
      GIT_REV: ${ELECTRS_GIT_REV:-}
      NJOBS: ${NJOBS:-}

services:
  bitcoind:
    <<: *build-bitcoin
    command: bitcoind -datadir=/bitcoin -chain=${BITCOIN_CHAIN} -rpcbind=0.0.0.0:8332 ${BITCOIN_ARGS:-}
    restart: unless-stopped
    volumes:
      - ${BITCOIN_DATADIR}:/bitcoin
    configs:
      - source: bitcoin 
        target: /bitcoin/bitcoin.conf
    expose:
      - 8332

  bitcoin-cli:
    <<: *build-bitcoin
    entrypoint: bitcoin-cli -datadir=/bitcoin -rpcconnect=bitcoind -rpcport=8332 -rpcwallet=main
    volumes:
      - ${BITCOIN_DATADIR}:/bitcoin:ro
    configs:
      - source: bitcoin 
        target: /bitcoin/bitcoin.conf
    depends_on:
      bitcoind:
        condition: service_started

  electrs:
    <<: *build-electrs
    command: electrs --conf=/etc/electrs.toml
    restart: unless-stopped
    depends_on:
      bitcoind:
        restart: true
        condition: service_started
    volumes:
      - ${ELECTRS_DATADIR}:/data/electrs
      - ${BITCOIN_DATADIR}:/data/bitcoin:ro
    configs:
      - source: electrs
        target: /etc/electrs.toml
    environment:
      - RUST_BACKTRACE=1
    expose:
      - 50001

configs:
  bitcoin:
    file: ./configs/${BITCOIN_CONF}
  electrs:
    file: ./configs/${ELECTRS_CONF}
