x-bitcoin-build: &build-bitcoin
  user: ${DOCKER_UID_GID}
  build:
    context: ./docker/bitcoin
    args:
      GIT_URL: ${BITCOIN_GIT_URL}
      GIT_BRANCH: ${BITCOIN_GIT_BRANCH}
      NJOBS: ${NJOBS}

x-electrs-build: &build-electrs
  build:
    context: ./docker/electrs
    args:
      GIT_URL: ${ELECTRS_GIT_URL:-https://github.com/romanz/electrs}
      GIT_BRANCH: ${ELECTRS_GIT_BRANCH:-master}
      GIT_REV: ${ELECTRS_GIT_REV:-}
      NJOBS: ${NJOBS:-}

services:
  bitcoind:
    <<: *build-bitcoin
    command: bitcoind -datadir=/.bitcoin ${BITCOIN_ARGS}
    restart: unless-stopped
    volumes:
      - ${BITCOIN_DATADIR}:/.bitcoin/${BITCOIN_CHAIN}
    configs:
      - source: bitcoin 
        target: /.bitcoin/bitcoin.conf

  bitcoin-cli:
    <<: *build-bitcoin
    entrypoint: bitcoin-cli -rpcconnect=bitcoind -rpcwallet=main -datadir=/.bitcoin
    volumes:
      - ${BITCOIN_DATADIR}:/.bitcoin/${BITCOIN_CHAIN}
    configs:
      - source: bitcoin 
        target: /.bitcoin/bitcoin.conf

  electrs:
    <<: *build-electrs
    command: electrs --network=${BITCOIN_CHAIN} --conf=/etc/electrs.toml
    restart: unless-stopped
    depends_on:
      bitcoind:
        restart: true
        condition: service_started
    volumes:
      - ${ELECTRS_DATADIR}:/data/electrs
      - ${BITCOIN_DATADIR}:/data/bitcoin/${BITCOIN_CHAIN}
    configs:
      - source: electrs
        target: /etc/electrs.toml

configs:
  bitcoin:
    file: ./configs/${BITCOIN_CONF}
  electrs:
    file: ./configs/${ELECTRS_CONF}
