x-bitcoin-build: &build-bitcoin
  build:
    context: ./docker/bitcoin
    dockerfile: ${BITCOIN_DOCKERFILE:-Dockerfile}
    args:
      GIT_URL: ${BITCOIN_GIT_URL:-https://github.com/bitcoin/bitcoin.git}
      GIT_BRANCH: ${BITCOIN_GIT_BRANCH:-v27.1}
      NJOBS: ${NJOBS:-4}

x-electrs-build: &build-electrs
  build:
    context: ./docker/electrs
    args:
      RUST_VERSION: ${ELECTRS_RUST_VERSION:-latest}
      GIT_URL: ${ELECTRS_GIT_URL:-https://github.com/romanz/electrs}
      GIT_BRANCH: ${ELECTRS_GIT_BRANCH:-}
      GIT_REV: ${ELECTRS_GIT_REV:-}
      GIT_TAG: ${ELECTRS_GIT_TAG:-}
      FEATURES: ${ELECTRS_FEATURES:-}
      NJOBS: ${NJOBS:-}

services:
  bitcoind:
    <<: *build-bitcoin
    command: bitcoind -datadir=/bitcoin -chain=${BITCOIN_CHAIN} -rpcbind=0.0.0.0:8332 ${BITCOIN_ARGS:-}
    restart: unless-stopped
    volumes:
      - ${BITCOIN_DATADIR}:/bitcoin
    configs:
      - source: bitcoin 
        target: /bitcoin/bitcoin.conf
    expose:
      - 8332
      - 8333

  bitcoin-cli:
    <<: *build-bitcoin
    entrypoint: bitcoin-cli -datadir=/bitcoin -rpcconnect=bitcoind -rpcport=8332 -rpcwallet=main
    volumes:
      - ${BITCOIN_DATADIR}:/bitcoin:ro
    configs:
      - source: bitcoin 
        target: /bitcoin/bitcoin.conf
    depends_on:
      bitcoind:
        condition: service_started

  electrs:
    <<: *build-electrs
    restart: unless-stopped
    depends_on:
      bitcoind:
        restart: true
        condition: service_started
    command:
      - electrs
      - --conf=/config/electrs.toml
      - --network=${ELECTRS_CHAIN}
      - --db-dir=/data/electrs
      - --daemon-dir=/data/bitcoin
      - --daemon-rpc-addr=bitcoind:8332
      - --daemon-p2p-addr=bitcoind:8333
      - --electrum-rpc-addr=0.0.0.0:50001
      - --monitoring-addr=0.0.0.0:4224
      - --server-banner=${ELECTRS_BANNER}
      - --log-filters=INFO
    configs:
      - source: electrs
        target: /config/electrs.toml
    expose:
      - 3000
      - 50001
      - 4224
    volumes:
      - ${ELECTRS_DATADIR}:/data/electrs
      - ${BITCOIN_DATADIR}:/data/bitcoin:ro
    environment:
      - RUST_BACKTRACE=full

configs:
  bitcoin:
    file: ./configs/${BITCOIN_CONF}
  electrs:
    file: ./configs/${ELECTRS_CONF}
