network = "signet"
db_dir = "/data/electrs"
daemon_dir = "/data/bitcoin"
daemon_rpc_addr = "bitcoind:8332"
daemon_p2p_addr = "bitcoind:8333"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters = "INFO"
monitoring_addr = "0.0.0.0:4224"
signet_magic="a5df2dcb"
